package com.ldq.financial.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.ldq.financial.dao.Record;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table record.
*/
public class RecordDao extends AbstractDao<Record, Long> {

    public static final String TABLENAME = "record";

    /**
     * Properties of entity Record.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RecordName = new Property(1, String.class, "recordName", false, "RECORD_NAME");
        public final static Property Value = new Property(2, float.class, "value", false, "VALUE");
        public final static Property IsPayment = new Property(3, boolean.class, "isPayment", false, "IS_PAYMENT");
        public final static Property Remarks = new Property(4, String.class, "remarks", false, "REMARKS");
        public final static Property CreateAt = new Property(5, long.class, "createAt", false, "CREATE_AT");
        public final static Property LastModify = new Property(6, long.class, "lastModify", false, "LAST_MODIFY");
        public final static Property CategoryId = new Property(7, long.class, "categoryId", false, "CATEGORY_ID");
        public final static Property Time = new Property(8, long.class, "time", false, "TIME");
    };

    private DaoSession daoSession;

    private Query<Record> category_RecordsQuery;

    public RecordDao(DaoConfig config) {
        super(config);
    }
    
    public RecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'record' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'RECORD_NAME' TEXT NOT NULL ," + // 1: recordName
                "'VALUE' REAL NOT NULL ," + // 2: value
                "'IS_PAYMENT' INTEGER NOT NULL ," + // 3: isPayment
                "'REMARKS' TEXT NOT NULL ," + // 4: remarks
                "'CREATE_AT' INTEGER NOT NULL ," + // 5: createAt
                "'LAST_MODIFY' INTEGER NOT NULL ," + // 6: lastModify
                "'CATEGORY_ID' INTEGER NOT NULL ," + // 7: categoryId
                "'TIME' INTEGER NOT NULL );"); // 8: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'record'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Record entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRecordName());
        stmt.bindDouble(3, entity.getValue());
        stmt.bindLong(4, entity.getIsPayment() ? 1l: 0l);
        stmt.bindString(5, entity.getRemarks());
        stmt.bindLong(6, entity.getCreateAt());
        stmt.bindLong(7, entity.getLastModify());
        stmt.bindLong(8, entity.getCategoryId());
        stmt.bindLong(9, entity.getTime());
    }

    @Override
    protected void attachEntity(Record entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Record readEntity(Cursor cursor, int offset) {
        Record entity = new Record( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // recordName
            cursor.getFloat(offset + 2), // value
            cursor.getShort(offset + 3) != 0, // isPayment
            cursor.getString(offset + 4), // remarks
            cursor.getLong(offset + 5), // createAt
            cursor.getLong(offset + 6), // lastModify
            cursor.getLong(offset + 7), // categoryId
            cursor.getLong(offset + 8) // time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Record entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRecordName(cursor.getString(offset + 1));
        entity.setValue(cursor.getFloat(offset + 2));
        entity.setIsPayment(cursor.getShort(offset + 3) != 0);
        entity.setRemarks(cursor.getString(offset + 4));
        entity.setCreateAt(cursor.getLong(offset + 5));
        entity.setLastModify(cursor.getLong(offset + 6));
        entity.setCategoryId(cursor.getLong(offset + 7));
        entity.setTime(cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Record entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Record entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "records" to-many relationship of Category. */
    public List<Record> _queryCategory_Records(long categoryId) {
        synchronized (this) {
            if (category_RecordsQuery == null) {
                QueryBuilder<Record> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CategoryId.eq(null));
                queryBuilder.orderRaw("TIME DESC");
                category_RecordsQuery = queryBuilder.build();
            }
        }
        Query<Record> query = category_RecordsQuery.forCurrentThread();
        query.setParameter(0, categoryId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCategoryDao().getAllColumns());
            builder.append(" FROM record T");
            builder.append(" LEFT JOIN category T0 ON T.'CATEGORY_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Record loadCurrentDeep(Cursor cursor, boolean lock) {
        Record entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Category category = loadCurrentOther(daoSession.getCategoryDao(), cursor, offset);
         if(category != null) {
            entity.setCategory(category);
        }

        return entity;    
    }

    public Record loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Record> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Record> list = new ArrayList<Record>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Record> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Record> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
